@startuml class caption 
package 實作抽象化 {

    abstract class 列印文件實作 {
        +列印()
        +開啟()
        +關閉()
    }

    class 列印字串實作 {

    }

    class 列印檔案實作 {

    }

}

package 功能抽象化 {
    class 列印文件 {
        -列印文件實作 實作
        +列印文件(列印文件實作 實作)
        +列印()
        +開啟()
        +關閉()
        +顯示()
    }

    class 列印指定次數 {
        +反覆列印(int times)
    }

    class 列印隨機次數{
        +隨機列印()
    }
}


列印文件實作 <|-- 列印字串實作
列印文件實作 <|-- 列印檔案實作


列印文件 <|-- 列印指定次數
列印文件 <|-- 列印隨機次數

列印文件 o- 列印文件實作

@enduml
